# Production overrides
# Applied on top of values.yaml by the namiview-app ArgoCD Application.

replicaCount: 2
image:
  tag: "prod-31-03-417c5d9"
app:
  googleRedirectUri: "https://namiview.com/api/auth/callback"
  corsOrigins: "https://namiview.com"
revisionHistoryLimit: 3
