# Production overrides
# Applied on top of values.yaml by the namiview-app ArgoCD Application.

replicaCount: 2
image:
  tag: "prod-15-03-845c4ba"
app:
  googleRedirectUri: "https://namiview.com/api/auth/callback"
  corsOrigins: "https://namiview.com"
