# Development / staging overrides
# Applied on top of values.yaml by the namiview-dev ArgoCD Application.

replicaCount: 1
image:
  tag: "dev-60-25-03-b98025a"
vault:
  paths:
    mongodbDb: namiview-dev/infra/mongodb/db
    minioBucket: namiview-dev/infra/minio/bucket
app:
  googleRedirectUri: "https://dev.namiview.com/api/auth/callback"
  corsOrigins: "https://dev.namiview.com"
revisionHistoryLimit: 3
PodDisruptionBudget:
  enabled: false
