# Development / staging overrides
# Applied on top of values.yaml by the namiview-dev ArgoCD Application.

replicaCount: 2

image:
  tag: "26-12-03-dev"

vault:
  paths:
    mongodbDb: namiview-dev/infra/mongodb/db
    minioBucket: namiview-dev/infra/minio/bucket
app:
  googleRedirectUri: "https://dev.namiview.com/api/auth/callback"
  corsOrigins: "https://dev.namiview.com"