apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "namiview.connectionSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namiview.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.vault.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "namiview.connectionSecretName" . }}
  data:
    - secretKey: MONGO_USER
      remoteRef:
        key: {{ .Values.vault.paths.mongodb }}
        property: username
    - secretKey: MONGO_PASSWORD
      remoteRef:
        key: {{ .Values.vault.paths.mongodb }}
        property: password
    - secretKey: MONGO_DB
      remoteRef:
        key: {{ .Values.vault.paths.mongodbDb }}
        property: name
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: {{ .Values.vault.paths.minio }}
        property: rootUser
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: {{ .Values.vault.paths.minio }}
        property: rootPassword
    - secretKey: MINIO_BUCKET
      remoteRef:
        key: {{ .Values.vault.paths.minioBucket }}
        property: name
    - secretKey: MINIO_SECURE
      remoteRef:
        key: {{ .Values.vault.paths.minioSecure }}
        property: value
