apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "namiview.googleCredsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namiview.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.vault.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "namiview.googleCredsSecretName" . }}
  data:
    - secretKey: google-creds.json
      remoteRef:
        key: {{ .Values.vault.paths.googleCreds }}
