apiVersion: v1
kind: Service
metadata:
  name: {{ include "namiview.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namiview.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "namiview.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityTimeoutSeconds }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
