apiVersion: v1
kind: Service
metadata:
  name: {{ include "namiview-triage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namiview-triage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "namiview-triage.selectorLabels" . | nindent 4 }}
