apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "namiview-api.dockercfgSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namiview-api.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.vault.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "namiview-api.dockercfgSecretName" . }}
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.vault.paths.dockerReg }}
        property: .dockerconfigjson
