apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "namiview-api.jwtSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namiview-api.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.vault.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "namiview-api.jwtSecretName" . }}
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.vault.paths.jwt }}
        property: JWT_SECRET
