apiVersion: v1
kind: Service
metadata:
  name: {{ include "namiview-api.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namiview-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "namiview-api.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityTimeoutSeconds }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
    {{- end }}
