# Production overrides
# Applied on top of values.yaml by the namiview-app ArgoCD Application.

replicaCount: 2
image:
  tag: "prod-26-03-81660ec"
app:
  googleRedirectUri: "https://namiview.com/api/auth/callback"
revisionHistoryLimit: 3
