# Production overrides
# Applied on top of values.yaml by the namiview-app ArgoCD Application.

replicaCount: 2
image:
  tag: "prod-31-03-9357303"
app:
  googleRedirectUri: "https://namiview.com/api/auth/callback"
revisionHistoryLimit: 3
