apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "namiview-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namiview-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "namiview-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "namiview-ui.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "namiview-ui.dockercfgSecretName" . }}
      containers:
        - name: namiview-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
            {{- end }}
          env:
            - name: GOOGLE_REDIRECT_URI
              value: {{ .Values.app.googleRedirectUri | quote }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/google_credentials.json"
          volumeMounts:
            - name: google-creds
              mountPath: "/app/google_credentials.json"
              subPath: "google_credentials.json"
              readOnly: true
      volumes:
        - name: google-creds
          secret:
            secretName: {{ include "namiview-ui.googleCredsSecretName" . }}
            items:
              - key: "google-creds.json"
                path: "google_credentials.json"
